<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <title>Welcome to Rick&#39;s Page  | 异常</title>
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">

    <meta name="viewport" content="width=device-width,minimum-scale=1">
    <meta name="generator" content="Hugo 0.91.2" />
    
    
      <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
    

    
    
      <link href="/rick/dist/css/app.955516233bcafa4d2a1c13cea63c7b50.css" rel="stylesheet">
    

    

    
      
    

    

    <meta property="og:title" content="异常" />
<meta property="og:description" content="异常 一、try、catch、throw 可以使用 throw 语句在代码块中的任何地方抛出异常。throw 语句的操作数可以是任意的表达式，表达式的结果的类型决定了抛出的异常的类型
int main( ) { try{ throw &#34;exception&#34;; }catch(const char * e){ cout &lt;&lt; e &lt;&lt; endl; }catch(...){ // 捕获所有异常  cout &lt;&lt; &#34;...&#34; &lt;&lt; endl; } { cout &lt;&lt; &#34;finally&#34; &lt;&lt; endl; } return 0; } Start exception finally 0 Finish 二、std::exception class exception { public: exception() throw(); exception(const exception&amp; rhs) throw(); exception&amp; operator=(const exception&amp; rhs) throw(); virtual ~exception() throw(); virtual const char *what() const throw(); }; 派生了两个异常类：" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://874656645.github.io/rick/posts/57-%E5%BC%82%E5%B8%B8/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2021-12-30T15:34:27+08:00" />
<meta property="article:modified_time" content="2021-12-30T15:34:27+08:00" />

<meta itemprop="name" content="异常">
<meta itemprop="description" content="异常 一、try、catch、throw 可以使用 throw 语句在代码块中的任何地方抛出异常。throw 语句的操作数可以是任意的表达式，表达式的结果的类型决定了抛出的异常的类型
int main( ) { try{ throw &#34;exception&#34;; }catch(const char * e){ cout &lt;&lt; e &lt;&lt; endl; }catch(...){ // 捕获所有异常  cout &lt;&lt; &#34;...&#34; &lt;&lt; endl; } { cout &lt;&lt; &#34;finally&#34; &lt;&lt; endl; } return 0; } Start exception finally 0 Finish 二、std::exception class exception { public: exception() throw(); exception(const exception&amp; rhs) throw(); exception&amp; operator=(const exception&amp; rhs) throw(); virtual ~exception() throw(); virtual const char *what() const throw(); }; 派生了两个异常类："><meta itemprop="datePublished" content="2021-12-30T15:34:27+08:00" />
<meta itemprop="dateModified" content="2021-12-30T15:34:27+08:00" />
<meta itemprop="wordCount" content="183">
<meta itemprop="keywords" content="" /><meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="异常"/>
<meta name="twitter:description" content="异常 一、try、catch、throw 可以使用 throw 语句在代码块中的任何地方抛出异常。throw 语句的操作数可以是任意的表达式，表达式的结果的类型决定了抛出的异常的类型
int main( ) { try{ throw &#34;exception&#34;; }catch(const char * e){ cout &lt;&lt; e &lt;&lt; endl; }catch(...){ // 捕获所有异常  cout &lt;&lt; &#34;...&#34; &lt;&lt; endl; } { cout &lt;&lt; &#34;finally&#34; &lt;&lt; endl; } return 0; } Start exception finally 0 Finish 二、std::exception class exception { public: exception() throw(); exception(const exception&amp; rhs) throw(); exception&amp; operator=(const exception&amp; rhs) throw(); virtual ~exception() throw(); virtual const char *what() const throw(); }; 派生了两个异常类："/>

  </head>

  <body class="ma0 avenir bg-near-white">

    
   
  

  <header>
    <div class="bg-black">
      <nav class="pv3 ph3 ph4-ns" role="navigation">
  <div class="flex-l justify-between items-center center">
    <a href="https://874656645.github.io/rick/" class="f3 fw2 hover-white no-underline white-90 dib">
      Welcome to Rick&#39;s Page
    </a>
    <div class="flex-l items-center">
      
      
<div hidden>
  <span id="new-window-0">Opens in a new window</span>
  <span id="new-window-1">Opens an external site</span>
  <span id="new-window-2">Opens an external site in a new window</span>
</div>









    </div>
  </div>
</nav>

    </div>
  </header>



    <main class="pb7" role="main">
      
  
  <article class="flex-l flex-wrap justify-between mw8 center ph3 ph0-l">

    <header class="mt4 w-100">
      <p class="f6 b helvetica tracked">
          
        POSTS
      </p>
      <h1 class="f1 athelas mb1">异常</h1>
      
      <time class="f6 mv4 dib tracked" datetime="2021-12-30T15:34:27&#43;08:00">December 30, 2021</time>      
      
      
    </header>

    <main class="nested-copy-line-height lh-copy serif f4 nested-links nested-img mid-gray pr4-l w-two-thirds-l"><h2 id="异常">异常</h2>
<h3 id="一trycatchthrow">一、try、catch、throw</h3>
<p>可以使用 throw 语句在代码块中的任何地方抛出异常。<strong>throw 语句的操作数可以是任意的表达式</strong>，表达式的结果的类型决定了抛出的异常的类型</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-C++" data-lang="C++"><span style="color:#66d9ef">int</span> <span style="color:#a6e22e">main</span>( )
{  
    <span style="color:#66d9ef">try</span>{
        <span style="color:#66d9ef">throw</span> <span style="color:#e6db74">&#34;exception&#34;</span>;
    }<span style="color:#66d9ef">catch</span>(<span style="color:#66d9ef">const</span> <span style="color:#66d9ef">char</span> <span style="color:#f92672">*</span> e){
        cout <span style="color:#f92672">&lt;&lt;</span> e <span style="color:#f92672">&lt;&lt;</span> endl;
    }<span style="color:#66d9ef">catch</span>(...){    <span style="color:#75715e">// 捕获所有异常
</span><span style="color:#75715e"></span>        cout <span style="color:#f92672">&lt;&lt;</span> <span style="color:#e6db74">&#34;...&#34;</span> <span style="color:#f92672">&lt;&lt;</span> endl;
    }
    {
        cout <span style="color:#f92672">&lt;&lt;</span> <span style="color:#e6db74">&#34;finally&#34;</span> <span style="color:#f92672">&lt;&lt;</span> endl;
    }
    
    <span style="color:#66d9ef">return</span> <span style="color:#ae81ff">0</span>;
}
</code></pre></div><div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-text" data-lang="text">Start
exception
finally
0
Finish
</code></pre></div><h3 id="二stdexception">二、std::exception</h3>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-C++" data-lang="C++"><span style="color:#66d9ef">class</span> <span style="color:#a6e22e">exception</span> {
<span style="color:#66d9ef">public</span><span style="color:#f92672">:</span>
   exception() <span style="color:#66d9ef">throw</span>();
   exception(<span style="color:#66d9ef">const</span> exception<span style="color:#f92672">&amp;</span> rhs) <span style="color:#66d9ef">throw</span>();
   exception<span style="color:#f92672">&amp;</span> <span style="color:#66d9ef">operator</span><span style="color:#f92672">=</span>(<span style="color:#66d9ef">const</span> exception<span style="color:#f92672">&amp;</span> rhs) <span style="color:#66d9ef">throw</span>();
   <span style="color:#66d9ef">virtual</span> <span style="color:#f92672">~</span>exception() <span style="color:#66d9ef">throw</span>();
   <span style="color:#66d9ef">virtual</span> <span style="color:#66d9ef">const</span> <span style="color:#66d9ef">char</span> <span style="color:#f92672">*</span><span style="color:#a6e22e">what</span>() <span style="color:#66d9ef">const</span> <span style="color:#66d9ef">throw</span>();
};
</code></pre></div><p><strong>派生了两个异常类：</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left">类名</th>
<th style="text-align:left">描述</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">logic_erro</td>
<td style="text-align:left">报告程序的逻辑错误，<strong>可在程序执行前被检测到</strong></td>
</tr>
<tr>
<td style="text-align:left">runtime_erro</td>
<td style="text-align:left">报告程序运行时的错误，只有在运行的时候才能检测到</td>
</tr>
</tbody>
</table>
<p><strong>由logic_erro派生的异常类：</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left">类名</th>
<th style="text-align:left">描述</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">domain_error</td>
<td style="text-align:left">报告违反了前置条件</td>
</tr>
<tr>
<td style="text-align:left">invalid_argument</td>
<td style="text-align:left">指出函数的一个无效参数</td>
</tr>
<tr>
<td style="text-align:left">length_error</td>
<td style="text-align:left">指出有一个产生超过NPOS长度的对象的企图（NPOS为size_t的最大可表现值</td>
</tr>
<tr>
<td style="text-align:left">out_of_range</td>
<td style="text-align:left">报告参数越界</td>
</tr>
<tr>
<td style="text-align:left">bad_cast</td>
<td style="text-align:left">在运行时类型识别中有一个无效的dynamic_cast表达式</td>
</tr>
<tr>
<td style="text-align:left">bad_typeid</td>
<td style="text-align:left">报告在表达式typeid(*p)中有一个空指针P</td>
</tr>
</tbody>
</table>
<p><strong>由runtime_error派生的异常：</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left">类名</th>
<th style="text-align:left">描述</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">range_error</td>
<td style="text-align:left">报告违反了后置条件</td>
</tr>
<tr>
<td style="text-align:left">overflow_error</td>
<td style="text-align:left">报告一个算术溢出</td>
</tr>
<tr>
<td style="text-align:left">bad_alloc</td>
<td style="text-align:left">报告一个存储分配错误</td>
</tr>
</tbody>
</table>
<p><img src="../img/exception.png" alt="std::exception"></p>
<h3 id="三自定义异常">三、自定义异常</h3>
<p>可以通过继承和重载 exception 类来定义新的异常</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-C++" data-lang="C++"><span style="color:#66d9ef">struct</span> <span style="color:#a6e22e">MyException</span> <span style="color:#f92672">:</span> <span style="color:#66d9ef">public</span> exception
{
  <span style="color:#66d9ef">const</span> <span style="color:#66d9ef">char</span> <span style="color:#f92672">*</span> <span style="color:#a6e22e">what</span> () <span style="color:#66d9ef">const</span> <span style="color:#66d9ef">throw</span> ()   <span style="color:#75715e">// 表明没有任何异常抛出
</span><span style="color:#75715e"></span>  {
    <span style="color:#66d9ef">return</span> <span style="color:#e6db74">&#34;C++ Exception&#34;</span>;
  }
};
 
<span style="color:#66d9ef">int</span> <span style="color:#a6e22e">main</span>()
{
    <span style="color:#66d9ef">try</span>
    {
        <span style="color:#66d9ef">throw</span> MyException();
    }
    <span style="color:#66d9ef">catch</span>(MyException<span style="color:#f92672">&amp;</span> e)
    {
        cout <span style="color:#f92672">&lt;&lt;</span> <span style="color:#e6db74">&#34;MyException caught&#34;</span> <span style="color:#f92672">&lt;&lt;</span> endl;
        cout <span style="color:#f92672">&lt;&lt;</span> e.what() <span style="color:#f92672">&lt;&lt;</span> endl;
    }
    <span style="color:#66d9ef">catch</span>(std<span style="color:#f92672">::</span>exception<span style="color:#f92672">&amp;</span> e)
    {
        <span style="color:#75715e">//其他的错误
</span><span style="color:#75715e"></span>    }
    <span style="color:#66d9ef">catch</span>(...)
    {
        cout <span style="color:#f92672">&lt;&lt;</span> <span style="color:#e6db74">&#34;...&#34;</span> <span style="color:#f92672">&lt;&lt;</span> endl;
    }
    {
        cout <span style="color:#f92672">&lt;&lt;</span> <span style="color:#e6db74">&#34;finally&#34;</span> <span style="color:#f92672">&lt;&lt;</span> endl;
    }
    <span style="color:#66d9ef">return</span> <span style="color:#ae81ff">0</span>;
}
</code></pre></div><div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-text" data-lang="text">Start
MyException caught
C++ Exception
finally
0
Finish
</code></pre></div><ul class="pa0">
  
</ul>
<div class="mt6">
        
      </div>
    </main>

    <aside class="w-30-l mt6-l">




</aside>

  </article>

    </main>
    <footer class="bg-black bottom-0 w-100 pa3" role="contentinfo">
  <div class="flex justify-between">
  <a class="f4 fw4 hover-white no-underline white-70 dn dib-ns pv2 ph3" href="https://874656645.github.io/rick/" >
    &copy; 2021 Welcome to Rick&#39;s Page
  </a>
    <div>
<div hidden>
  <span id="new-window-0">Opens in a new window</span>
  <span id="new-window-1">Opens an external site</span>
  <span id="new-window-2">Opens an external site in a new window</span>
</div>








</div>
  </div>
</footer>

    

  <script src="/rick/dist/js/app.3fc0f988d21662902933.js"></script>


  </body>
</html>
